# Generated by Django 6.0.3 on 2026-03-15 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_profileuser_resend_blocked_until_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="profileuser",
            name="reset_attempts",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="profileuser",
            name="reset_block_until",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="profileuser",
            name="reset_requested_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="profileuser",
            name="reset_token",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
