# Generated by Django 6.0.3 on 2026-04-23 15:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0008_alter_profileuser_is_active"),
    ]

    operations = [
        migrations.AddField(
            model_name="profileuser",
            name="referral_code",
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name="profileuser",
            name="referral_count",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="profileuser",
            name="referred_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
