# Generated by Django 6.0.3 on 2026-04-23 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "accounts",
            "0009_profileuser_referral_code_profileuser_referral_count_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="profileuser",
            name="referral_code",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
