# Generated by Django 6.0.3 on 2026-04-29 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0011_alter_profileuser_email_alter_profileuser_full_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profileuser",
            name="email",
            field=models.EmailField(max_length=60),
        ),
    ]
