# Generated by Django 6.0 on 2026-04-29 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("return", "0002_returnrequest_quantity"),
    ]

    operations = [
        migrations.AddField(
            model_name="returnrequest",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
