# Generated by Django 6.0.3 on 2026-03-17 19:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="address",
            options={"ordering": ["-is_default", "-created_at"]},
        ),
    ]
