# Generated by Django 6.0.3 on 2026-04-20 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0005_payment_razorpay_order_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="razorpay_order_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="payment",
            name="razorpay_payment_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="payment",
            name="razorpay_signature",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
