# Generated by Django 6.0 on 2026-04-21 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0007_alter_order_order_status_alter_orderitem_item_status_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="orderstatushistory",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="order",
            name="order_status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pending"),
                    ("CONFIRMED", "Confirmed"),
                    ("PROCESSING", "Processing"),
                    ("SHIPPED", "Shipped"),
                    ("OUT_FOR_DELIVERY", "Out for Delivery"),
                    ("DELIVERED", "Delivered"),
                    ("CANCELLED", "Cancelled"),
                    ("RETURNED", "Returned"),
                    ("PARTIALLY_RETURNED", "Partially Returned"),
                ],
                default="PENDING",
                max_length=30,
            ),
        ),
    ]
